### ISSUE TITLE
GHC 9.6.1

### ISSUE THREAD

**Issue by tbidne** [chessai/these-skinny#4]
Could we please have a new hackage revision? Seems to work with GHC 9.6.1 i.e no problems with `allow-newer: these-skinny:base`.

Thanks!

**Comment by chessai** [comment]
https://hackage.haskell.org/package/these-skinny-0.7.5/revisions/

Patch released

**Comment by tbidne** [comment]
Wow, fast. Thank you!

**Comment by chessai** [comment]
> Wow, fast.

Just like this package's compile times.
