### ISSUE TITLE
Release new version/revision for GHC 9.8

### ISSUE THREAD

**Issue by prikhi** [chessai/these-skinny#6]
Heya, could we get a release or metadata revision so dependent packages can start supporting GHC 9.8? Thanks!

**Comment by prikhi** [comment]
@chessai could we get a release or revision?

**Comment by tomjaguarpaw** [comment]
If it's just bounds bumping I suggest you file an issue with the Hackage Trustees: https://github.com/haskell-infra/hackage-trustees/issues

**Comment by tomjaguarpaw** [comment]
@chessai By the way, I'm willing to be a "maintainer who bumps bounds only" for this package, if you like.  [In fact probably more like "who makes trivial changes to make it work with future GHCs"]

**Comment by chessai** [comment]
revision released

**Comment by yaitskov** [comment]
The library's only source file is changed 6 years ago.
Why not just relax constraints in cabal file to minimize bureaucracy?!

**Comment by chessai** [comment]
> The library's only source file is changed 6 years ago.
> Why not just relax constraints in cabal file to minimize bureaucracy?!

Please PR it :)

**Comment by prikhi** [comment]
ty for the revision, bounds seem relaxed, gonna close this
